spring.application.name=makemytrip

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/makemytrip?sslMode=VERIFY_IDENTITY
spring.datasource.username=saJa1cxqYQqvwe2.root
spring.datasource.password=jCum250efZ7wmsWo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8081